GET http://127.0.0.1:3000/producto

### Guardar
POST http://127.0.0.1:3000/producto
Content-Type: application/json

{
    "nombre": "silla",
    "estado": true,
    "precio": 230
}

### Mostrar
GET http://127.0.0.1:3000/producto/1

### Modificar
PATCH  http://127.0.0.1:3000/producto/2
Content-Type: application/json

{   
    "nombre": "si funciona"
}

### Eliminar
DELETE http://127.0.0.1:3000/producto/2